import { Weekdays, Weekends } from './WeekData';
import { Languages } from './Languages';
import { SupportedCalendars } from './SupportedCalendars';
import { CountryCodes } from './CountryCodes';

interface CountryInfo {
  f: string;
  l: Languages;
  wd?: Weekdays;
  we?: Weekends;
  c?: SupportedCalendars;
}

type TypeCountries = {
  [key in CountryCodes]: CountryInfo;
};

export const Countries: TypeCountries = {
  AC: { f: '🇦🇨', l: Languages.en },
  AD: { f: '🇦🇩', l: Languages.ca },
  AE: { f: '🇦🇪', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  AF: {
    f: '🇦🇫',
    l: Languages.fa,
    c: SupportedCalendars.persian,
    wd: [6, 0, 1, 2, 3, 4, 5],
    we: [4, 5],
  },
  AG: { f: '🇦🇬', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  AI: { f: '🇦🇮', l: Languages.en },
  AL: { f: '🇦🇱', l: Languages.sq },
  AM: { f: '🇦🇲', l: Languages.hy },
  AO: { f: '🇦🇴', l: Languages.pt },
  AR: { f: '🇦🇷', l: Languages.es },
  AS: { f: '🇦🇸', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  AT: { f: '🇦🇹', l: Languages.de },
  AU: { f: '🇦🇺', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  AW: { f: '🇦🇼', l: Languages.nl },
  AX: { f: '🇦🇽', l: Languages.sv },
  AZ: { f: '🇦🇿', l: Languages.az },
  BA: { f: '🇧🇦', l: Languages.bs },
  BB: { f: '🇧🇧', l: Languages.en },
  BD: { f: '🇧🇩', l: Languages.bn, wd: [0, 1, 2, 3, 4, 5, 6] },
  BE: { f: '🇧🇪', l: Languages.en },
  BF: { f: '🇧🇫', l: Languages.fr },
  BG: { f: '🇧🇬', l: Languages.bg },
  BH: { f: '🇧🇭', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  BI: { f: '🇧🇮', l: Languages.rn },
  BJ: { f: '🇧🇯', l: Languages.fr },
  BL: { f: '🇧🇱', l: Languages.fr },
  BM: { f: '🇧🇲', l: Languages.en },
  BN: { f: '🇧🇳', l: Languages.ms },
  BO: { f: '🇧🇴', l: Languages.es },
  BQ: { f: '🇧🇶', l: Languages.nl },
  BR: { f: '🇧🇷', l: Languages.pt, wd: [0, 1, 2, 3, 4, 5, 6] },
  BS: { f: '🇧🇸', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  BT: { f: '🇧🇹', l: Languages.dz, wd: [0, 1, 2, 3, 4, 5, 6] },
  BW: { f: '🇧🇼', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  BY: { f: '🇧🇾', l: Languages.be },
  BZ: { f: '🇧🇿', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  CA: { f: '🇨🇦', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  CC: { f: '🇨🇨', l: Languages.en },
  CD: { f: '🇨🇩', l: Languages.fr },
  CF: { f: '🇨🇫', l: Languages.fr },
  CG: { f: '🇨🇬', l: Languages.fr },
  CH: { f: '🇨🇭', l: Languages.de },
  CI: { f: '🇨🇮', l: Languages.fr },
  CK: { f: '🇨🇰', l: Languages.en },
  CL: { f: '🇨🇱', l: Languages.es },
  CM: { f: '🇨🇲', l: Languages.fr },
  CN: { f: '🇨🇳', l: Languages.zh, wd: [0, 1, 2, 3, 4, 5, 6] },
  CO: { f: '🇨🇴', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  CR: { f: '🇨🇷', l: Languages.es },
  CU: { f: '🇨🇺', l: Languages.es },
  CV: { f: '🇨🇻', l: Languages.pt },
  CW: { f: '🇨🇼', l: Languages.nl },
  CX: { f: '🇨🇽', l: Languages.en },
  CY: { f: '🇨🇾', l: Languages.el },
  CZ: { f: '🇨🇿', l: Languages.cs },
  DE: { f: '🇩🇪', l: Languages.de },
  DG: { f: '🇩🇬', l: Languages.en },
  DJ: { f: '🇩🇯', l: Languages.aa, wd: [6, 0, 1, 2, 3, 4, 5] },
  DK: { f: '🇩🇰', l: Languages.da },
  DM: { f: '🇩🇲', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  DO: { f: '🇩🇴', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  DZ: { f: '🇩🇿', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  EA: { f: '🇪🇦', l: Languages.es },
  EC: { f: '🇪🇨', l: Languages.es },
  EE: { f: '🇪🇪', l: Languages.et },
  EG: { f: '🇪🇬', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  EH: { f: '🇪🇭', l: Languages.ar },
  ER: { f: '🇪🇷', l: Languages.ti },
  ES: { f: '🇪🇸', l: Languages.es },
  ET: { f: '🇪🇹', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  FI: { f: '🇫🇮', l: Languages.fi },
  FJ: { f: '🇫🇯', l: Languages.en },
  FK: { f: '🇫🇰', l: Languages.en },
  FM: { f: '🇫🇲', l: Languages.en },
  FO: { f: '🇫🇴', l: Languages.fo },
  FR: { f: '🇫🇷', l: Languages.fr },
  GA: { f: '🇬🇦', l: Languages.fr },
  GB: { f: '🇬🇧', l: Languages.en },
  GD: { f: '🇬🇩', l: Languages.en },
  GE: { f: '🇬🇪', l: Languages.ka },
  GF: { f: '🇬🇫', l: Languages.fr },
  GG: { f: '🇬🇬', l: Languages.en },
  GH: { f: '🇬🇭', l: Languages.en },
  GI: { f: '🇬🇮', l: Languages.en },
  GL: { f: '🇬🇱', l: Languages.kl },
  GM: { f: '🇬🇲', l: Languages.en },
  GN: { f: '🇬🇳', l: Languages.fr },
  GP: { f: '🇬🇵', l: Languages.fr },
  GQ: { f: '🇬🇶', l: Languages.es },
  GR: { f: '🇬🇷', l: Languages.el },
  GT: { f: '🇬🇹', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  GU: { f: '🇬🇺', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  GW: { f: '🇬🇼', l: Languages.pt },
  GY: { f: '🇬🇾', l: Languages.en },
  HK: { f: '🇭🇰', l: Languages.zh, wd: [0, 1, 2, 3, 4, 5, 6] },
  HN: { f: '🇭🇳', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  HR: { f: '🇭🇷', l: Languages.hr },
  HT: { f: '🇭🇹', l: Languages.ht },
  HU: { f: '🇭🇺', l: Languages.hu },
  IC: { f: '🇮🇨', l: Languages.es },
  ID: { f: '🇮🇩', l: Languages.id, wd: [0, 1, 2, 3, 4, 5, 6] },
  IE: { f: '🇮🇪', l: Languages.en },
  IL: { f: '🇮🇱', l: Languages.he, wd: [0, 1, 2, 3, 4, 5, 6], we: [5, 6] },
  IM: { f: '🇮🇲', l: Languages.en },
  IN: { f: '🇮🇳', l: Languages.hi, wd: [0, 1, 2, 3, 4, 5, 6], we: [0] },
  IO: { f: '🇮🇴', l: Languages.en },
  IQ: { f: '🇮🇶', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  IR: {
    f: '🇮🇷',
    l: Languages.fa,
    c: SupportedCalendars.persian,
    wd: [6, 0, 1, 2, 3, 4, 5],
    we: [5],
  },
  IS: { f: '🇮🇸', l: Languages.is },
  IT: { f: '🇮🇹', l: Languages.it },
  JE: { f: '🇯🇪', l: Languages.en },
  JM: { f: '🇯🇲', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  JO: { f: '🇯🇴', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  JP: { f: '🇯🇵', l: Languages.ja, wd: [0, 1, 2, 3, 4, 5, 6] },
  KE: { f: '🇰🇪', l: Languages.sw, wd: [0, 1, 2, 3, 4, 5, 6] },
  KG: { f: '🇰🇬', l: Languages.ky },
  KH: { f: '🇰🇭', l: Languages.km, wd: [0, 1, 2, 3, 4, 5, 6] },
  KI: { f: '🇰🇮', l: Languages.en },
  KM: { f: '🇰🇲', l: Languages.ar },
  KN: { f: '🇰🇳', l: Languages.en },
  KP: { f: '🇰🇵', l: Languages.ko },
  KR: { f: '🇰🇷', l: Languages.ko, wd: [0, 1, 2, 3, 4, 5, 6] },
  KW: { f: '🇰🇼', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  KY: { f: '🇰🇾', l: Languages.en },
  KZ: { f: '🇰🇿', l: Languages.ru },
  LA: { f: '🇱🇦', l: Languages.lo, wd: [0, 1, 2, 3, 4, 5, 6] },
  LB: { f: '🇱🇧', l: Languages.ar },
  LC: { f: '🇱🇨', l: Languages.en },
  LI: { f: '🇱🇮', l: Languages.de },
  LK: { f: '🇱🇰', l: Languages.si },
  LR: { f: '🇱🇷', l: Languages.en },
  LS: { f: '🇱🇸', l: Languages.st },
  LT: { f: '🇱🇹', l: Languages.lt },
  LU: { f: '🇱🇺', l: Languages.fr },
  LV: { f: '🇱🇻', l: Languages.lv },
  LY: { f: '🇱🇾', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  MA: { f: '🇲🇦', l: Languages.fr },
  MC: { f: '🇲🇨', l: Languages.fr },
  MD: { f: '🇲🇩', l: Languages.ro },
  ME: { f: '🇲🇪', l: Languages.sq },
  MF: { f: '🇲🇫', l: Languages.fr },
  MG: { f: '🇲🇬', l: Languages.mg },
  MH: { f: '🇲🇭', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  MK: { f: '🇲🇰', l: Languages.mk },
  ML: { f: '🇲🇱', l: Languages.bm },
  MM: { f: '🇲🇲', l: Languages.my, wd: [0, 1, 2, 3, 4, 5, 6] },
  MN: { f: '🇲🇳', l: Languages.mn },
  MO: { f: '🇲🇴', l: Languages.zh, wd: [0, 1, 2, 3, 4, 5, 6] },
  MP: { f: '🇲🇵', l: Languages.en },
  MQ: { f: '🇲🇶', l: Languages.fr },
  MR: { f: '🇲🇷', l: Languages.ar },
  MS: { f: '🇲🇸', l: Languages.en },
  MT: { f: '🇲🇹', l: Languages.mt, wd: [0, 1, 2, 3, 4, 5, 6] },
  MU: { f: '🇲🇺', l: Languages.en },
  MV: { f: '🇲🇻', l: Languages.dv, wd: [5, 6, 0, 1, 2, 3, 4] },
  MW: { f: '🇲🇼', l: Languages.en },
  MX: { f: '🇲🇽', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  MY: { f: '🇲🇾', l: Languages.ms },
  MZ: { f: '🇲🇿', l: Languages.pt, wd: [0, 1, 2, 3, 4, 5, 6] },
  NA: { f: '🇳🇦', l: Languages.af },
  NC: { f: '🇳🇨', l: Languages.fr },
  NE: { f: '🇳🇪', l: Languages.ha },
  NF: { f: '🇳🇫', l: Languages.en },
  NG: { f: '🇳🇬', l: Languages.en },
  NI: { f: '🇳🇮', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  NL: { f: '🇳🇱', l: Languages.nl },
  NO: { f: '🇳🇴', l: Languages.nb },
  NP: { f: '🇳🇵', l: Languages.ne, wd: [0, 1, 2, 3, 4, 5, 6] },
  NR: { f: '🇳🇷', l: Languages.en },
  NU: { f: '🇳🇺', l: Languages.en },
  NZ: { f: '🇳🇿', l: Languages.en },
  OM: { f: '🇴🇲', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  PA: { f: '🇵🇦', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  PE: { f: '🇵🇪', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  PF: { f: '🇵🇫', l: Languages.fr },
  PG: { f: '🇵🇬', l: Languages.en },
  PH: { f: '🇵🇭', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  PK: { f: '🇵🇰', l: Languages.ur, wd: [0, 1, 2, 3, 4, 5, 6] },
  PL: { f: '🇵🇱', l: Languages.pl },
  PM: { f: '🇵🇲', l: Languages.fr },
  PN: { f: '🇵🇳', l: Languages.en },
  PR: { f: '🇵🇷', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  PS: { f: '🇵🇸', l: Languages.ar },
  PT: { f: '🇵🇹', l: Languages.pt, wd: [0, 1, 2, 3, 4, 5, 6] },
  PW: { f: '🇵🇼', l: Languages.en },
  PY: { f: '🇵🇾', l: Languages.gn, wd: [0, 1, 2, 3, 4, 5, 6] },
  QA: { f: '🇶🇦', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  RE: { f: '🇷🇪', l: Languages.fr },
  RO: { f: '🇷🇴', l: Languages.ro },
  RS: { f: '🇷🇸', l: Languages.sr },
  RU: { f: '🇷🇺', l: Languages.ru },
  RW: { f: '🇷🇼', l: Languages.rw },
  SA: {
    f: '🇸🇦',
    l: Languages.ar,
    c: SupportedCalendars.islamic,
    wd: [0, 1, 2, 3, 4, 5, 6],
    we: [5, 6],
  },
  SB: { f: '🇸🇧', l: Languages.en },
  SC: { f: '🇸🇨', l: Languages.fr },
  SD: { f: '🇸🇩', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  SE: { f: '🇸🇪', l: Languages.sv },
  SG: { f: '🇸🇬', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  SH: { f: '🇸🇭', l: Languages.en },
  SI: { f: '🇸🇮', l: Languages.sl },
  SJ: { f: '🇸🇯', l: Languages.nb },
  SK: { f: '🇸🇰', l: Languages.sk },
  SL: { f: '🇸🇱', l: Languages.en },
  SM: { f: '🇸🇲', l: Languages.it },
  SN: { f: '🇸🇳', l: Languages.wo },
  SO: { f: '🇸🇴', l: Languages.so },
  SR: { f: '🇸🇷', l: Languages.nl },
  SS: { f: '🇸🇸', l: Languages.ar },
  ST: { f: '🇸🇹', l: Languages.pt },
  SV: { f: '🇸🇻', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  SX: { f: '🇸🇽', l: Languages.en },
  SY: { f: '🇸🇾', l: Languages.ar, wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  SZ: { f: '🇸🇿', l: Languages.en },
  TA: { f: '🇹🇦', l: Languages.en },
  TC: { f: '🇹🇨', l: Languages.en },
  TD: { f: '🇹🇩', l: Languages.fr },
  TF: { f: '🇹🇫', l: Languages.fr },
  TG: { f: '🇹🇬', l: Languages.fr },
  TH: {
    f: '🇹🇭',
    l: Languages.th,
    c: SupportedCalendars.buddhist,
    wd: [0, 1, 2, 3, 4, 5, 6],
  },
  TJ: { f: '🇹🇯', l: Languages.tg },
  TK: { f: '🇹🇰', l: Languages.en },
  TL: { f: '🇹🇱', l: Languages.pt },
  TM: { f: '🇹🇲', l: Languages.tk },
  TN: { f: '🇹🇳', l: Languages.ar },
  TO: { f: '🇹🇴', l: Languages.to },
  TR: { f: '🇹🇷', l: Languages.tr },
  TT: { f: '🇹🇹', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  TV: { f: '🇹🇻', l: Languages.en },
  TW: { f: '🇹🇼', l: Languages.zh, wd: [0, 1, 2, 3, 4, 5, 6] },
  TZ: { f: '🇹🇿', l: Languages.sw },
  UA: { f: '🇺🇦', l: Languages.ru },
  UG: { f: '🇺🇬', l: Languages.sw, we: [0] },
  UM: { f: '🇺🇲', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  US: { f: '🇺🇸', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  UY: { f: '🇺🇾', l: Languages.es },
  UZ: { f: '🇺🇿', l: Languages.uz },
  VA: { f: '🇻🇦', l: Languages.it },
  VC: { f: '🇻🇨', l: Languages.en },
  VE: { f: '🇻🇪', l: Languages.es, wd: [0, 1, 2, 3, 4, 5, 6] },
  VG: { f: '🇻🇬', l: Languages.en },
  VI: { f: '🇻🇮', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  VN: { f: '🇻🇳', l: Languages.vi },
  VU: { f: '🇻🇺', l: Languages.bi },
  WF: { f: '🇼🇫', l: Languages.fr },
  WS: { f: '🇼🇸', l: Languages.sm, wd: [0, 1, 2, 3, 4, 5, 6] },
  XK: { f: '🇽🇰', l: Languages.sq },
  YE: { f: '🇾🇪', l: Languages.ar, wd: [0, 1, 2, 3, 4, 5, 6], we: [5, 6] },
  YT: { f: '🇾🇹', l: Languages.fr },
  ZA: { f: '🇿🇦', l: Languages.en, wd: [0, 1, 2, 3, 4, 5, 6] },
  ZM: { f: '🇿🇲', l: Languages.en },
  ZW: { f: '🇿🇼', l: Languages.sn, wd: [0, 1, 2, 3, 4, 5, 6] },
};
