export enum Languages {
  aa = 'aa',
  af = 'af',
  ar = 'ar',
  az = 'az',
  be = 'be',
  bg = 'bg',
  bi = 'bi',
  bm = 'bm',
  bn = 'bn',
  bs = 'bs',
  ca = 'ca',
  cs = 'cs',
  da = 'da',
  de = 'de',
  dv = 'dv',
  dz = 'dz',
  el = 'el',
  en = 'en',
  es = 'es',
  et = 'et',
  fa = 'fa',
  fi = 'fi',
  fo = 'fo',
  fr = 'fr',
  gn = 'gn',
  ha = 'ha',
  he = 'he',
  hi = 'hi',
  hr = 'hr',
  ht = 'ht',
  hu = 'hu',
  hy = 'hy',
  id = 'id',
  is = 'is',
  it = 'it',
  ja = 'ja',
  ka = 'ka',
  kl = 'kl',
  km = 'km',
  ko = 'ko',
  ky = 'ky',
  lo = 'lo',
  lt = 'lt',
  lv = 'lv',
  mg = 'mg',
  mk = 'mk',
  mn = 'mn',
  ms = 'ms',
  mt = 'mt',
  my = 'my',
  nb = 'nb',
  ne = 'ne',
  nl = 'nl',
  pl = 'pl',
  pt = 'pt',
  ps = 'ps',
  rn = 'rn',
  ro = 'ro',
  ru = 'ru',
  rw = 'rw',
  si = 'si',
  sk = 'sk',
  sl = 'sl',
  sm = 'sm',
  sn = 'sn',
  so = 'so',
  sq = 'sq',
  sr = 'sr',
  st = 'st',
  sv = 'sv',
  sw = 'sw',
  tg = 'tg',
  th = 'th',
  ti = 'ti',
  tk = 'tk',
  to = 'to',
  tr = 'tr',
  ur = 'ur',
  uz = 'uz',
  vi = 'vi',
  wo = 'wo',
  yi = 'yi',
  zh = 'zh',
}

export const LanguageArray = Object.keys(Languages);

export const RightToLeftLanguages: Languages[] = [
  Languages.ar,
  Languages.dv,
  Languages.fa,
  Languages.he,
  Languages.ps,
  Languages.ur,
  Languages.yi,
];

export const RightToLeftLanguagesArray = Object.keys(RightToLeftLanguages);
